### ISSUE TITLE
panic: Failed to auth. 403 Forbidden

### ISSUE THREAD

**Issue by gthbdcm** [Sorrow446/Napster-Downloader#10]
Trying to download an album the following error messages appears:
_panic: Failed to auth.
403 Forbidden_

Downloading worked until some days ago. My credentials and the config.json kept the same. With the same credentials I am able to login on the web page and via the Android app.
Tried it with https://play.napster.com/album/alb.503008846 (also tried it with web instead of play in the URL) and other albums.

The error message part after the "403 Forbidden" a bit different with the Linux binary downloaded from github and the Go version which includes the Issue #9 fix:

Binary:
_goroutine 1 [running]:
main.handleErr({0x7f094c, 0xf}, {0x867be0, 0xc0005af070}, 0x1)
	G:/go/napster_lossless/main.go:75 +0xc5
main.main()
	G:/go/napster_lossless/main.go:675 +0x10d_

Go version, with Issue #9:
_goroutine 1 [running]:
main.handleErr({0x800d84, 0xf}, {0x8998e0?, 0xc0004f8040?}, 0x1)
	/home/abc/Napster-Downloader-main/main.go:75 +0xc5
main.main()
	/home/abc/Napster-Downloader-main/main.go:680 +0x10d_

**Comment by Sorrow446** [comment]
They must've changed their API, will check soon. Can also be caused by being in certain countries, FYI.

**Comment by gthbdcm** [comment]
The account is subscribed to Napster Argentina. The error occurs when trying to download from a different country.
However, logging in and streaming with the Android app and the browser works (without VPN).

**Comment by Sorrow446** [comment]
Oh. Could you send me your creds over Discord?

**Comment by gthbdcm** [comment]
I sent a request in Discord. tomorrow...

**Comment by damarges** [comment]
Any Updates on If/when a fix can be implemented. Sorry for bothering you

**Comment by Sorrow446** [comment]
Logging into the web player with a VPN sometimes works, it's really weird.
