### ISSUE TITLE
panic while backslash in album title 

### ISSUE THREAD

**Issue by ghost** [Sorrow446/Napster-Downloader#14]
Example: panic: mkdir c:\xxx\albums\Interpret Album \ Remastered 2024): The system cannot find the path specified.

goroutine 1 [running]:
main.handleErr({0xdda820?, 0xc0002a03f0?}, 0x14?)
        G:/go/nap_vids/main.go:69 +0x79
main.main()
        G:/go/nap_vids/main.go:745 +0x2ae

**Comment by Sorrow446** [comment]
Fixing this would break using folders in the album templates.

https://github.com/Sorrow446/Napster-Downloader/blob/main/main.go#L447
Pass `false` instead of `true` and slashes will get sanitised as well.
